[package]
name = "amgix-now"
version = "0.1.0"
edition = "2024"

[features]
cuda = ["embed_anything/cuda"]
metal = ["embed_anything/metal"]

[dependencies]
axum = "0.8.9"
chrono = { version = "0.4.44", features = ["serde"] }
murmurhash3 = "0.0.5"
once_cell = "1.21.4"
regex = "1.12.3"
rust-stemmers = "1.2.0"
rustc-hash = "2.1.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
nu-ansi-term = "0.50.3"
stopwords = "0.1.1"
rayon = "1.12.0"
tokio = { version = "1.52.2", features = ["rt-multi-thread", "macros", "net", "signal", "sync"] }
unicode-segmentation = "1.13.2"
uuid = { version = "1.23.1", features = ["v4", "v5"] }
qdrant-client = "1.17.0"
embed_anything = { git = "https://github.com/amgix-dev/EmbedAnything.git", rev = "d7933c5476212c6adbe520a07037923f9db15c13", default-features = false, features = ["rustls-tls"] }
candle-core = "=0.11.0"
candle-transformers = "=0.11.0"
tokenizers = { version = "=0.22.2", default-features = false }
hf-hub = { version = "=0.4.3", default-features = false, features = ["ureq"] }
lapin = { version = "4.10.0", default-features = false, features = ["rustls", "tokio"] }
whatlang = "0.18.0"
isolang = "2.4.0"
pest = "2.8.6"
pest_derive = "2.8.6"
sysinfo = { version = "0.39.3", default-features = false, features = ["system"] }
flate2 = "1.1.9"
tokio-stream = "0.1.18"
bytes = "1.12.1"
nvml-wrapper = "0.12.1"
